// <auto-generated />
using FriendsCorner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FriendsCorner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FriendsCornerDb))]
    [Migration("20260928020259_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FriendsCorner.Infrastructure.Persistence.ChessRow", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fen");

                    b.Property<string>("WhiteSeat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("white_seat");

                    b.HasKey("RoomId");

                    b.ToTable("chess", (string)null);
                });

            modelBuilder.Entity("FriendsCorner.Infrastructure.Persistence.TicTacToeRow", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("NextSeat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("next_seat");

                    b.Property<string>("Squares")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .HasColumnName("squares");

                    b.HasKey("RoomId");

                    b.ToTable("tic_tac_toe", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
