// <auto-generated />
using System;
using FriendsCorner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FriendsCorner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FriendsCornerDb))]
    [Migration("20261001015420_AddHostPlans")]
    partial class AddHostPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FriendsCorner.Infrastructure.Persistence.ChessRow", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fen");

                    b.Property<string>("WhiteSeat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("white_seat");

                    b.HasKey("RoomId");

                    b.ToTable("chess", (string)null);
                });

            modelBuilder.Entity("FriendsCorner.Infrastructure.Persistence.LetterTilesRow", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.HasKey("RoomId");

                    b.ToTable("letter_tiles", (string)null);
                });

            modelBuilder.Entity("FriendsCorner.Infrastructure.Persistence.MysteryRow", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.HasKey("RoomId");

                    b.ToTable("mystery_games", (string)null);
                });

            modelBuilder.Entity("FriendsCorner.Infrastructure.Persistence.TicTacToeRow", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("NextSeat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("next_seat");

                    b.Property<string>("Squares")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .HasColumnName("squares");

                    b.HasKey("RoomId");

                    b.ToTable("tic_tac_toe", (string)null);
                });

            modelBuilder.Entity("FriendsCorner.Infrastructure.Persistence.UserRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BillingEventAt")
                        .HasColumnType("bigint")
                        .HasColumnName("billing_event_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Plan")
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_customer_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StripeCustomerId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
