<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\FriendsCorner.Core\FriendsCorner.Core.csproj" />
    <ProjectReference Include="..\FriendsCorner.Infrastructure\FriendsCorner.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3786614e-2ca9-4323-9f1a-5c6704fc1662</UserSecretsId>
  </PropertyGroup>

</Project>
